Install pip from cwl-ica conda env by exporting path first
umccr/cwl-ica pull request #31
Opened 2021-09-30 02:38 UTC by alexiswl

Added to debug investigation of pip setuptools error

2021-09-30 02:44 UTC, alexiswl commented
Will revert back and use single quotes

2021-09-30 03:17 UTC, scwatts requested changes

2021-09-30 03:17 UTC, scwatts commented on .github/scripts/run_sync-tools_and_sync-workflows.sh
> +  bash -c 'pip install setuptools<58'
The command responsible for triggering is:
```
conda run ['bash', '-c', 'pip install setuptools<58']
```

But needs to read:
```
conda run ['bash', '-c', 'pip install "setuptools<58"']
```

So the quoting needed here is:
```
bash -c 'pip install "setuptools<58"'
```

2021-09-30 04:08 UTC, scwatts approved these changes

2021-09-30 04:19 UTC, alexiswl commented
I think I'll just build a container for cwl-ica instead. Looks like it takes six minutes to even just install the basics. Could be useful from user endpoint too.

2021-09-30 06:36 UTC, scwatts approved these changes

2021-10-01 01:37 UTC, alexiswl commented
Thanks for your help debugging this Stephen, setuptools in conda env has worked and have created a docker image for amd and arm users too (which strips down a lot of the GH actions workflow too). Tested on separate ec2 instance and sync runs fine! Documentation on using container locally still to come. Will also deploy new release after this merge.

2021-10-01 01:37 UTC, merged