Fix/dragen germline tool
umccr/cwl-ica pull request #319
Opened 2023-04-06 01:09 UTC by skanwal

Fixes https://github.com/umccr/cwl-ica/issues/316

2023-04-06 02:09 UTC, alexiswl commented
Did you also wish to sync the dragen-germline-pipeline and dragen-somatic-with-germline-pipeline as well?

2023-04-06 02:10 UTC, alexiswl commented
> Did you also wish to sync the dragen-germline-pipeline and dragen-somatic-with-germline-pipeline as well?

Actually maybe wait for #318 to complete first

2023-04-06 02:10 UTC, alexiswl requested changes

2023-04-06 02:10 UTC, alexiswl commented on tools/dragen-germline/4.0.3/dragen-germline__4.0.3.cwl
>              echo "Please set no more than one of fastq_list, fastq_list_rows and bam_input for normal sample" 1>&2
Should be _echo "Please set one AND only one of ..._

2023-04-06 02:18 UTC, alexiswl commented
Converted to draft as I need to re-push to #318 due to a syntax error in the somatic pipeline.

2023-04-18 01:48 UTC, skanwal commented
@alexiswl - updated in https://github.com/umccr/cwl-ica/pull/319/commits/c0b9174e2b3a885825c9459ba4022f0b9a97045e

2023-04-18 01:52 UTC, alexiswl approved these changes

2023-04-18 03:17 UTC, merged